[project]
name = "crdr-wacv"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "numpy<2",
    "torch==1.12.1+cu113",
    "torchvision==0.13.1+cu113",
    "torchaudio==0.12.1",
    "compressai==1.2.4",
    "opencv-python==4.5.5.62",
    "pandas==1.4.1",
    "python-log-indenter>=0.9",
    "tqdm>=4.66.4",
    "pyyaml>=6.0.1",
    "addict>=2.4.0",
    "lpips>=0.1.4",
    "pytorch-fid>=0.3.0",
    "scikit-image==0.19.3",
    "dists-pytorch>=0.1",
    "vmaf-torch>=0.1",
]

[tool.uv.sources]
torch = { index = "torch_cu113" }
torchvision = { index = "torch_cu113" }
torchaudio = { index = "torch_cu113" }

[[tool.uv.index]]
name = "torch_cu113"
url = "https://download.pytorch.org/whl/cu113"
explicit = true

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
